# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c3097c4e21f488c6f639adcab1da65b69fe07c858da023c6c141f11c70fab2be430887aec5a652c5b4f6558dffca4b2510071f888746cb7e92635b118f443cb2

test:
  secret_key_base: a34daa9286b07d1b174c33d8f8b23416b5193d7111eb42725994da2eb29eb7a2d22353767ece9fff2a805916686fd27af9a3338572ce652742e4b0887121968d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
